
version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - echo 'Entered install ...'
      - apt-get update -y
  build:
    commands:
      - make build
    
  test:
    commands:
      - make test-cover

artifacts:
  files:
    - '*/ci-test'
    - '*/coverage.html'
  name: ci-test-$(date +%Y-%m-%d)